"""Initial schema with agent_states, execution_results, and plan_run_states

Revision ID: 4990121b40b7
Revises: 
Create Date: 2025-11-17 14:29:39.722324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4990121b40b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable UUID extension for PostgreSQL
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compressed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('state_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'execution_id', name='unique_agent_execution')
    )
    op.create_index('idx_agent_states_agent_created', 'agent_states', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_agent_states_state_data', 'agent_states', ['state_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_agent_states_agent_id'), 'agent_states', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_states_created_at'), 'agent_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_states_execution_id'), 'agent_states', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_states_trace_id'), 'agent_states', ['trace_id'], unique=False)
    op.create_table('execution_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failure', 'timeout', 'cancelled')", name='check_execution_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_results_agent_status', 'execution_results', ['agent_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_execution_results_result_data', 'execution_results', ['result_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_execution_results_agent_id'), 'execution_results', ['agent_id'], unique=False)
    op.create_index(op.f('ix_execution_results_created_at'), 'execution_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_results_execution_id'), 'execution_results', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_results_status'), 'execution_results', ['status'], unique=False)
    op.create_index(op.f('ix_execution_results_task_id'), 'execution_results', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_results_trace_id'), 'execution_results', ['trace_id'], unique=False)
    op.create_table('plan_run_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('plan_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('participating_agents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('final_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'failed', 'cancelled')", name='check_plan_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_run_states_execution_history', 'plan_run_states', ['execution_history'], unique=False, postgresql_using='gin')
    op.create_index('idx_plan_run_states_plan_definition', 'plan_run_states', ['plan_definition'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_plan_run_states_created_at'), 'plan_run_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_run_states_plan_id'), 'plan_run_states', ['plan_id'], unique=True)
    op.create_index(op.f('ix_plan_run_states_status'), 'plan_run_states', ['status'], unique=False)
    op.create_index(op.f('ix_plan_run_states_trace_id'), 'plan_run_states', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_run_states_trace_id'), table_name='plan_run_states')
    op.drop_index(op.f('ix_plan_run_states_status'), table_name='plan_run_states')
    op.drop_index(op.f('ix_plan_run_states_plan_id'), table_name='plan_run_states')
    op.drop_index(op.f('ix_plan_run_states_created_at'), table_name='plan_run_states')
    op.drop_index('idx_plan_run_states_plan_definition', table_name='plan_run_states', postgresql_using='gin')
    op.drop_index('idx_plan_run_states_execution_history', table_name='plan_run_states', postgresql_using='gin')
    op.drop_table('plan_run_states')
    op.drop_index(op.f('ix_execution_results_trace_id'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_task_id'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_status'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_execution_id'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_created_at'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_agent_id'), table_name='execution_results')
    op.drop_index('idx_execution_results_result_data', table_name='execution_results', postgresql_using='gin')
    op.drop_index('idx_execution_results_agent_status', table_name='execution_results')
    op.drop_table('execution_results')
    op.drop_index(op.f('ix_agent_states_trace_id'), table_name='agent_states')
    op.drop_index(op.f('ix_agent_states_execution_id'), table_name='agent_states')
    op.drop_index(op.f('ix_agent_states_created_at'), table_name='agent_states')
    op.drop_index(op.f('ix_agent_states_agent_id'), table_name='agent_states')
    op.drop_index('idx_agent_states_state_data', table_name='agent_states', postgresql_using='gin')
    op.drop_index('idx_agent_states_agent_created', table_name='agent_states')
    op.drop_table('agent_states')
    # ### end Alembic commands ###
